prompt --install
#omu
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/admin_lookup_values.sql
@@application/shared_components/navigation/lists/admin_notifications.sql
@@application/shared_components/navigation/lists/recent_projects.sql
@@application/shared_components/navigation/lists/admin_monitoring.sql
@@application/shared_components/navigation/lists/feedback.sql
@@application/shared_components/navigation/lists/reports.sql
@@application/shared_components/navigation/lists/admin_utilities.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/admin_access_control.sql
@@application/shared_components/navigation/lists/admin_configuration.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/strategic_planner_png.sql
@@application/shared_components/files/strategic_planner_transparent_png.sql
@@application/shared_components/files/default_user_avatar_png.sql
@@application/shared_components/files/js_sp_search_min_js.sql
@@application/shared_components/files/js_sp_search_js.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/set_navigation_strings.sql
@@application/shared_components/logic/application_processes/viewprojectpdf.sql
@@application/shared_components/logic/application_processes/viewreleasepdf.sql
@@application/shared_components/logic/application_processes/viewinitiativepdf.sql
@@application/shared_components/logic/application_processes/viewinitfocusareapdf.sql
@@application/shared_components/logic/application_processes/viewtaskpdf.sql
@@application/shared_components/logic/application_processes/initialize_nomenclature.sql
@@application/shared_components/logic/application_processes/set_app_home_url_if_null.sql
@@application/shared_components/logic/application_items/app_user_first_last_name.sql
@@application/shared_components/logic/application_items/app_user_id.sql
@@application/shared_components/logic/application_items/complete_task_status_ids.sql
@@application/shared_components/logic/application_items/focus_area.sql
@@application/shared_components/logic/application_items/initiative.sql
@@application/shared_components/logic/application_items/is_admin.sql
@@application/shared_components/logic/application_items/last_project_view.sql
@@application/shared_components/logic/application_items/last_proj_jump_pg.sql
@@application/shared_components/logic/application_items/nomenclature_area.sql
@@application/shared_components/logic/application_items/nomenclature_areas.sql
@@application/shared_components/logic/application_items/nomenclature_contributor.sql
@@application/shared_components/logic/application_items/nomenclature_contributors.sql
@@application/shared_components/logic/application_items/nomenclature_initiative.sql
@@application/shared_components/logic/application_items/nomenclature_initiatives.sql
@@application/shared_components/logic/application_items/nomenclature_project.sql
@@application/shared_components/logic/application_items/nomenclature_projects.sql
@@application/shared_components/logic/application_items/nomenclature_strategic_planner.sql
@@application/shared_components/logic/application_items/nomenclature_user.sql
@@application/shared_components/logic/application_items/nomenclature_users.sql
@@application/shared_components/logic/application_items/project.sql
@@application/shared_components/logic/application_computations/is_admin.sql
@@application/shared_components/logic/application_computations/app_user_id.sql
@@application/shared_components/logic/application_computations/app_user_first_last_name.sql
@@application/shared_components/logic/application_computations/last_project_view.sql
@@application/shared_components/logic/application_computations/complete_task_status_ids.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/area_initiative_2.sql
@@application/shared_components/user_interface/lovs/email_alert_pref.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/projects_detail.sql
@@application/shared_components/user_interface/lovs/releases.sql
@@application/shared_components/user_interface/lovs/sp_areas_area.sql
@@application/shared_components/user_interface/lovs/sp_groups_group_name.sql
@@application/shared_components/user_interface/lovs/sp_initiatives_initiative.sql
@@application/shared_components/user_interface/lovs/sp_projects_project.sql
@@application/shared_components/user_interface/lovs/sp_release_trains_release_train.sql
@@application/shared_components/user_interface/lovs/sp_resource_types_resource_type.sql
@@application/shared_components/user_interface/lovs/sp_team_members.sql
@@application/shared_components/user_interface/lovs/sp_team_members_current_only.sql
@@application/shared_components/user_interface/lovs/sp_team_members_first_name.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_due.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_initiated.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_priority.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_state.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_type.sql
@@application/shared_components/user_interface/lovs/workflow_console_lov_initiated.sql
@@application/shared_components/user_interface/lovs/workflow_console_lov_workflow_state.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/report/kanban_grid.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/email/templates/project_related.sql
@@application/shared_components/email/templates/notif_subscriptions_job.sql
@@application/shared_components/email/templates/email_me.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/plugins/template_component/content_row.sql
@@application/shared_components/plugins/template_component/theme_42_content_row64393.sql
@@application/shared_components/navigation/search_config/project_search.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00075.sql
@@application/pages/page_00076.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00079.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00083.sql
@@application/pages/page_00084.sql
@@application/pages/page_00085.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_00090.sql
@@application/pages/page_00091.sql
@@application/pages/page_00092.sql
@@application/pages/page_00093.sql
@@application/pages/page_00094.sql
@@application/pages/page_00095.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00103.sql
@@application/pages/page_00104.sql
@@application/pages/page_00105.sql
@@application/pages/page_00106.sql
@@application/pages/page_00107.sql
@@application/pages/page_00108.sql
@@application/pages/page_00109.sql
@@application/pages/page_00110.sql
@@application/pages/page_00111.sql
@@application/pages/page_00113.sql
@@application/pages/page_00114.sql
@@application/pages/page_00115.sql
@@application/pages/page_00116.sql
@@application/pages/page_00117.sql
@@application/pages/page_00118.sql
@@application/pages/page_00119.sql
@@application/pages/page_00120.sql
@@application/pages/page_00122.sql
@@application/pages/page_00123.sql
@@application/pages/page_00124.sql
@@application/pages/page_00128.sql
@@application/pages/page_00129.sql
@@application/pages/page_00130.sql
@@application/pages/page_00131.sql
@@application/pages/page_00135.sql
@@application/pages/page_00136.sql
@@application/pages/page_00137.sql
@@application/pages/page_00138.sql
@@application/pages/page_00139.sql
@@application/pages/page_00140.sql
@@application/pages/page_00141.sql
@@application/pages/page_00144.sql
@@application/pages/page_00145.sql
@@application/pages/page_00149.sql
@@application/pages/page_00150.sql
@@application/pages/page_00151.sql
@@application/pages/page_00152.sql
@@application/pages/page_00154.sql
@@application/pages/page_00155.sql
@@application/pages/page_00160.sql
@@application/pages/page_00161.sql
@@application/pages/page_00162.sql
@@application/pages/page_00163.sql
@@application/pages/page_00164.sql
@@application/pages/page_00200.sql
@@application/pages/page_00202.sql
@@application/pages/page_00203.sql
@@application/pages/page_00222.sql
@@application/pages/page_00300.sql
@@application/pages/page_00500.sql
@@application/pages/page_00501.sql
@@application/pages/page_00502.sql
@@application/pages/page_00503.sql
@@application/pages/page_00504.sql
@@application/pages/page_00505.sql
@@application/pages/page_00506.sql
@@application/pages/page_00507.sql
@@application/pages/page_00508.sql
@@application/pages/page_00509.sql
@@application/pages/page_00600.sql
@@application/pages/page_00610.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10011.sql
@@application/pages/page_10012.sql
@@application/pages/page_10013.sql
@@application/pages/page_10014.sql
@@application/pages/page_10050.sql
@@application/pages/page_10061.sql
@@application/pages/page_10062.sql
@@application/pages/page_10064.sql
@@application/pages/page_10065.sql
@@application/pages/page_10074.sql
@@application/pages/page_10087.sql
@@application/pages/page_10090.sql
@@application/pages/page_10091.sql
@@application/pages/page_10100.sql
@@application/pages/page_10101.sql
@@application/pages/page_10150.sql
@@application/pages/page_10151.sql
@@application/pages/page_10200.sql
@@application/pages/page_10210.sql
@@application/pages/page_10400.sql
@@application/pages/page_10410.sql
@@application/pages/page_10500.sql
@@application/pages/page_10510.sql
@@application/pages/page_10520.sql
@@application/pages/page_10600.sql
@@application/pages/page_10601.sql
@@application/pages/page_10610.sql
@@application/pages/page_10700.sql
@@application/pages/page_10710.sql
@@application/pages/page_10750.sql
@@application/pages/page_10760.sql
@@application/pages/page_10770.sql
@@application/pages/page_10780.sql
@@application/pages/page_10800.sql
@@application/pages/page_10810.sql
@@application/pages/page_10820.sql
@@application/pages/page_11300.sql
@@application/pages/page_11310.sql
@@application/pages/page_11320.sql
@@application/pages/page_12120.sql
@@application/pages/page_12121.sql
@@application/pages/page_12123.sql
@@application/pages/page_12124.sql
@@application/pages/page_12130.sql
@@application/pages/page_12140.sql
@@application/pages/page_12150.sql
@@application/pages/page_14000.sql
@@application/pages/page_14001.sql
@@application/pages/page_14010.sql
@@application/pages/page_15021.sql
@@application/pages/page_16010.sql
@@application/pages/page_16011.sql
@@application/pages/page_16015.sql
@@application/pages/page_16016.sql
@@application/pages/page_16017.sql
@@application/pages/page_16020.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_sequences.sql
@@application/deployment/install/install_sp_globals.sql
@@application/deployment/install/install_sp_strategic_proj_util_spec.sql
@@application/deployment/install/install_sp_contributor_summary_spec.sql
@@application/deployment/install/install_sp_release_timeline_package_spec.sql
@@application/deployment/install/install_app_log.sql
@@application/deployment/install/install_sp_app_settings.sql
@@application/deployment/install/install_default_tags_table.sql
@@application/deployment/install/install_app_nomenclature_table.sql
@@application/deployment/install/install_resource_types_table.sql
@@application/deployment/install/install_create_table_sp_competencies.sql
@@application/deployment/install/install_create_table_sp_groups.sql
@@application/deployment/install/install_team_members_table.sql
@@application/deployment/install/install_sp_group_members.sql
@@application/deployment/install/install_release_trains_table.sql
@@application/deployment/install/install_sp_release_history.sql
@@application/deployment/install/install_areas_table.sql
@@application/deployment/install/install_project_scales_table.sql
@@application/deployment/install/install_initiatives_tables.sql
@@application/deployment/install/install_sp_project_priorities_table.sql
@@application/deployment/install/install_project_sizes.sql
@@application/deployment/install/install_create_project_groups_table.sql
@@application/deployment/install/install_initiative_focus_areas_tables.sql
@@application/deployment/install/install_projects_tables.sql
@@application/deployment/install/install_project_history.sql
@@application/deployment/install/install_project_link_tables.sql
@@application/deployment/install/install_project_comments_tables.sql
@@application/deployment/install/install_release_comments_table.sql
@@application/deployment/install/install_app_pages_table.sql
@@application/deployment/install/install_sp_release_milestone_types_table_and_trigger.sql
@@application/deployment/install/install_release_milestones_table.sql
@@application/deployment/install/install_release_documents_table_and_triggr.sql
@@application/deployment/install/install_package_sp_value_compare.sql
@@application/deployment/install/install_countries_table.sql
@@application/deployment/install/install_external_system_names.sql
@@application/deployment/install/install_triggers.sql
@@application/deployment/install/install_sp_notifications_table.sql
@@application/deployment/install/install_sp_notification_subscriptions.sql
@@application/deployment/install/install_create_sp_areas_trigger.sql
@@application/deployment/install/install_release_trains_triggers.sql
@@application/deployment/install/install_create_sp_team_members_trigger.sql
@@application/deployment/install/install_sp_group_members_trigger.sql
@@application/deployment/install/install_sp_competencies_trigger.sql
@@application/deployment/install/install_sp_groups_trigger.sql
@@application/deployment/install/install_initiatives_triggers.sql
@@application/deployment/install/install_initiative_focus_area_triggers.sql
@@application/deployment/install/install_project_comments_triggers.sql
@@application/deployment/install/install_project_contributors_triggers.sql
@@application/deployment/install/install_release_comments_triggers.sql
@@application/deployment/install/install_project_documents_triggers.sql
@@application/deployment/install/install_project_links_triggers.sql
@@application/deployment/install/install_related_projects_trigger.sql
@@application/deployment/install/install_projects_triggers.sql
@@application/deployment/install/install_release_milestone_triggers.sql
@@application/deployment/install/install_proj_interactions_log_table.sql
@@application/deployment/install/install_activity_types_table.sql
@@application/deployment/install/install_activity_types_triggers.sql
@@application/deployment/install/install_sp_activities_table.sql
@@application/deployment/install/install_sp_activities_trigger.sql
@@application/deployment/install/install_sp_date_range_pct_comp_function.sql
@@application/deployment/install/install_sp_tag_diff_function.sql
@@application/deployment/install/install_favorites_table.sql
@@application/deployment/install/install_favorite_toggle_procedure.sql
@@application/deployment/install/install_configurable_text_table.sql
@@application/deployment/install/install_sp_default_people_tags_table.sql
@@application/deployment/install/install_sp_default_people_tags_trigger.sql
@@application/deployment/install/install_create_sp_application_notifications.sql
@@application/deployment/install/install_initiative_comments_table_and_trigger.sql
@@application/deployment/install/install_create_table_sp_release_links.sql
@@application/deployment/install/install_initiative_links_table_and_trigger.sql
@@application/deployment/install/install_initiative_documents_table_and_trigger.sql
@@application/deployment/install/install_project_task_tables.sql
@@application/deployment/install/install_project_task_triggers.sql
@@application/deployment/install/install_team_member_notifications.sql
@@application/deployment/install/install_sp_contributor_summary_body.sql
@@application/deployment/install/install_sp_release_timeline_package_body.sql
@@application/deployment/install/install_sp_strategic_proj_util_body.sql
@@application/deployment/install/install_seed_countries.sql
@@application/deployment/install/install_seed_nomenclature.sql
@@application/deployment/install/install_seed_external_ticketing_systems.sql
@@application/deployment/install/install_seed_resource_types.sql
@@application/deployment/install/install_seed_project_scales.sql
@@application/deployment/install/install_seed_default_tags.sql
@@application/deployment/install/install_seed_project_priorities.sql
@@application/deployment/install/install_seed_project_sizes.sql
@@application/deployment/install/install_seed_activity_types.sql
@@application/deployment/install/install_seed_release_milestone_types.sql
@@application/deployment/install/install_seed_settings.sql
@@application/deployment/install/install_seed_notifications.sql
@@application/deployment/install/install_seed_competencies.sql
@@application/deployment/install/install_seed_task_types_and_statuses.sql
@@application/deployment/install/install_create_sample_data.sql
@@application/deployment/install/install_notifications_job.sql
@@application/deployment/install/install_seed_first_user.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
